apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: hello-container
    image: hub.comcast.net/dx_svsops_platformoperations/alpine:latest
    command: ["echo", "hello"]
